server:
  port: 8080
spring:
  application:
    name: homework
security:
  admin:
    username: admin
    password: 111qqq
  default:
    username: user
    password: 111222
logging:
  level:
    root: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

app:
  version: ${app:version:1.0.0}
